const arr = [
    'create',
    'inventory',
    'screenshot',
    'recover',
    'add',
    'arrow_rigth',
    'close_$ccc',
    'dw',
    'fm',
    'heart',
    'icon_video',
    'menu',
    'more',
    'more_gray',
    'music_fill',
    'music_black',
    'pitch',
    'search',
    'video',
    'collect',
    'calendar',
    'selected',
    'arrow_right_$fff',
    'live',
    'vip',
    'vip_fill',
    'comment',
    'forward',
    'address',
    'alarm_clock_1',
    'alarm_clock_2',
    'clothes',
    'coupon',
    'game',
    'listen_music',
    'messages',
    'night_mode',
    'order',
    'people',
    'quit',
    'recorder',
    'scan',
    'security',
    'settings',
    'shopCart',
    'small_bell',
    'ticket',
    'weibo',
    'weixin',
    'qq',
    'wangyi',
    'defalut_avatar',
    'integral',
    'logo',
    'ranking',
    'radio_2',
    'video_fill',
    'radio_1',
    'a',
    'space',
    'rate_2_fill',
    'rate_1_fill',
    'user_search',
]

let obj = {}
arr.forEach(item =>{
    obj[item] = require(`@/assets/${item}.png`)
})

export default obj